import json
import os

# Create proper tokenizer for test model
tokenizer_config = {
    "version": "1.0",
    "truncation": None,
    "padding": None,
    "added_tokens": [],
    "normalizer": None,
    "pre_tokenizer": None,
    "post_processor": None,
    "decoder": None,
    "model": {
        "type": "BPE",
        "vocab": {
            "!": 0,
            "\"": 1,
            "#": 2,
            "$": 3,
            "%": 4,
            "&": 5,
            "'": 6,
            "(": 7,
            ")": 8,
            "*": 9,
            "+": 10,
            ",": 11,
            "-": 12,
            ".": 13,
            "/": 14,
            "0": 15,
            "1": 16,
            "2": 17,
            "3": 18,
            "4": 19,
            "5": 20,
            "6": 21,
            "7": 22,
            "8": 23,
            "9": 24,
            ":": 25,
            ";": 26,
            "<": 27,
            "=": 28,
            ">": 29,
            "?": 30,
            "@": 31,
            "A": 32,
            "B": 33,
            "C": 34,
            "D": 35,
            "E": 36,
            "F": 37,
            "G": 38,
            "H": 39,
            "I": 40,
            "J": 41,
            "K": 42,
            "L": 43,
            "M": 44,
            "N": 45,
            "O": 46,
            "P": 47,
            "Q": 48,
            "R": 49,
            "S": 50,
            "T": 51,
            "U": 52,
            "V": 53,
            "W": 54,
            "X": 55,
            "Y": 56,
            "Z": 57,
            "[": 58,
            "\\": 59,
            "]": 60,
            "^": 61,
            "_": 62,
            "`": 63,
            "a": 64,
            "b": 65,
            "c": 66,
            "d": 67,
            "e": 68,
            "f": 69,
            "g": 70,
            "h": 71,
            "i": 72,
            "j": 73,
            "k": 74,
            "l": 75,
            "m": 76,
            "n": 77,
            "o": 78,
            "p": 79,
            "q": 80,
            "r": 81,
            "s": 82,
            "t": 83,
            "u": 84,
            "v": 85,
            "w": 86,
            "x": 87,
            "y": 88,
            "z": 89,
            "{": 90,
            "|": 91,
            "}": 92,
            "~": 93,
            " ": 94,
            "\n": 95,
            "\t": 96,
            "[UNK]": 97,
            "[CLS]": 98,
            "[SEP]": 99,
            "[PAD]": 100,
            "[MASK]": 101
        },
        "merges": []
    }
}

# Create models directory if it doesn't exist
os.makedirs("clients/models/test-model", exist_ok=True)

# Save tokenizer.json
with open("clients/models/test-model/tokenizer.json", "w") as f:
    json.dump(tokenizer_config, f, indent=2)

print("✓ Fixed tokenizer.json created")
print(f"  Location: clients/models/test-model/tokenizer.json")
print(f"  Size: {os.path.getsize('clients/models/test-model/tokenizer.json')} bytes")