#if !canImport(ObjectiveC)
import XCTest

extension CreateAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateAccountTests = [
        ("testNoNetwork", testNoNetwork),
        ("testSimple", testSimple),
    ]
}

extension CreateFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateFileTests = [
        ("testDeepFileCreation", testDeepFileCreation),
    ]
}

extension ExportAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExportAccountTests = [
        ("testSimple", testSimple),
    ]
}

extension ImportAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImportAccountTests = [
        ("testBadAccountString", testBadAccountString),
        ("testSimple", testSimple),
    ]
}

extension SyncTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyncTests = [
        ("testBruteNoFiles", testBruteNoFiles),
        ("testBruteSomeFiles", testBruteSomeFiles),
        ("testIterativeNoFiles", testIterativeNoFiles),
        ("testIterativeSomeFiles", testIterativeSomeFiles),
    ]
}

extension UsageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsageTests = [
        ("testSimple", testSimple),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CreateAccountTests.__allTests__CreateAccountTests),
        testCase(CreateFileTests.__allTests__CreateFileTests),
        testCase(ExportAccountTests.__allTests__ExportAccountTests),
        testCase(ImportAccountTests.__allTests__ImportAccountTests),
        testCase(SyncTests.__allTests__SyncTests),
        testCase(UsageTests.__allTests__UsageTests),
    ]
}
#endif
