#if !canImport(ObjectiveC)
import XCTest

extension CreateAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateAccountTests = [
        ("testNoNetwork", testNoNetwork),
        ("testSimple", testSimple),
    ]
}

extension CreateFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateFileTests = [
        ("testDeepFileCreation", testDeepFileCreation),
    ]
}

extension DbMigrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DbMigrationTests = [
        ("testMustGetStateFirst", testMustGetStateFirst),
        ("testSimple", testSimple),
        ("testTryMigrateWhenReadyToUse", testTryMigrateWhenReadyToUse),
        ("testTryMigrateWhenRequiresCleaning", testTryMigrateWhenRequiresCleaning),
    ]
}

extension ErrorEnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorEnumTests = [
        ("testAllVariants", testAllVariants),
    ]
}

extension ExportAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExportAccountTests = [
        ("testSimple", testSimple),
    ]
}

extension ImportAccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImportAccountTests = [
        ("testBadAccountString", testBadAccountString),
        ("testSimple", testSimple),
    ]
}

extension ModifyFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModifyFileTests = [
        ("testRename", testRename),
        ("testUpdateContent10MB", testUpdateContent10MB),
        ("testUpdateContent1KB", testUpdateContent1KB),
        ("testUpdateContent1MB", testUpdateContent1MB),
    ]
}

extension SyncFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SyncFileTests = [
        ("testBruteNoFiles", testBruteNoFiles),
        ("testBruteSomeFiles", testBruteSomeFiles),
        ("testIterativeNoFiles", testIterativeNoFiles),
        ("testIterativeSomeFiles", testIterativeSomeFiles),
    ]
}

extension UsageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsageTests = [
        ("testSimple", testSimple),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CreateAccountTests.__allTests__CreateAccountTests),
        testCase(CreateFileTests.__allTests__CreateFileTests),
        testCase(DbMigrationTests.__allTests__DbMigrationTests),
        testCase(ErrorEnumTests.__allTests__ErrorEnumTests),
        testCase(ExportAccountTests.__allTests__ExportAccountTests),
        testCase(ImportAccountTests.__allTests__ImportAccountTests),
        testCase(ModifyFileTests.__allTests__ModifyFileTests),
        testCase(SyncFileTests.__allTests__SyncFileTests),
        testCase(UsageTests.__allTests__UsageTests),
    ]
}
#endif
