#if !canImport(ObjectiveC)
import XCTest

extension ErrorEnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorEnumTests = [
        ("testAllVariants", testAllVariants),
    ]
}

extension FFITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FFITests = [
        ("testBadAccountString", testBadAccountString),
        ("testBruteNoFiles", testBruteNoFiles),
        ("testBruteSomeFiles", testBruteSomeFiles),
        ("testBruteSomeFilesLocalChanges", testBruteSomeFilesLocalChanges),
        ("testDeepFileCreation", testDeepFileCreation),
        ("testIterativeNoFiles", testIterativeNoFiles),
        ("testLocalChangesNoFiles", testLocalChangesNoFiles),
        ("testMissingFile", testMissingFile),
        ("testNoNetwork", testNoNetwork),
        ("testRename", testRename),
        ("testSimple", testSimple),
        ("testSimpleDelete", testSimpleDelete),
        ("testSimpleImportExport", testSimpleImportExport),
        ("testUpdateContent10MB", testUpdateContent10MB),
        ("testUpdateContent1KB", testUpdateContent1KB),
        ("testUpdateContent1MB", testUpdateContent1MB),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ErrorEnumTests.__allTests__ErrorEnumTests),
        testCase(FFITests.__allTests__FFITests),
    ]
}
#endif
