//! Re-export Phosphor glyphs used by the editor context menu.
//!
//! Source of truth: [`crate::theme::phosphor`] (same set as the toolbar).

pub use crate::theme::phosphor::{
    APP_WINDOW, ARROWS_CLOCKWISE, ARROW_SQUARE_OUT, ARROW_U_UP_LEFT, ARROW_U_UP_RIGHT,
    CARET_DOUBLE_UP, CLIPBOARD, CODE, CODE_BLOCK, COPY, EYE_SLASH, HIGHLIGHTER_CIRCLE, LINK,
    LIST_BULLETS, LIST_CHECKS, LIST_NUMBERS, MAGNIFYING_GLASS, PARAGRAPH, PENCIL_SIMPLE, QUOTES,
    SCISSORS, SELECTION_ALL, TEXT_AA, TEXT_B, TEXT_H_FIVE, TEXT_H_FOUR, TEXT_H_ONE, TEXT_H_SIX,
    TEXT_H_THREE, TEXT_H_TWO, TEXT_INDENT, TEXT_ITALIC, TEXT_OUTDENT, TEXT_STRIKETHROUGH,
    TEXT_SUBSCRIPT, TEXT_SUPERSCRIPT, TEXT_UNDERLINE,
};
