base_url = "https://lockbook.net"
title = "Lockbook"
description = "Lockbook is an open-source notebook for markdown notes and SVG drawings, encrypted on your device and shared only by invitation."

compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
lazy_async_image = true

[extra]
