base_url = "https://lockbook.net"
title = "Lockbook"
description = "An open-source, end-to-end encrypted notebook."

compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
lazy_async_image = true

[extra]
