use ignore::gitignore::{Gitignore, GitignoreBuilder};
use std::fs;
use std::path::Path;

const BUILTIN_DEFAULTS: &[&str] = &[
    ".git/",
    "*.sqlite",
    "*.sqlite-shm",
    "*.sqlite-wal",
    "node_modules/",
    "target/",
    "__pycache__/",
    ".DS_Store",
    ".sync-dir-state",
];

const DEFAULT_FILE_CONTENTS: &str = "\
# .lockbookignore — generated by lockbook sync-dir
# Patterns below are ignored by default even without this file.
# Add your own exclusions after the defaults.

.git/
*.sqlite
*.sqlite-shm
*.sqlite-wal
node_modules/
target/
__pycache__/
.DS_Store
.sync-dir-state
";

pub struct IgnoreRules {
    matcher: Gitignore,
}

impl IgnoreRules {
    /// Load ignore rules from .lockbookignore at the sync root, merged with built-in defaults.
    pub fn load(sync_root: &Path) -> Self {
        let mut builder = GitignoreBuilder::new(sync_root);

        // Built-in defaults always apply
        for pattern in BUILTIN_DEFAULTS {
            builder.add_line(None, pattern).ok();
        }

        // Load user .lockbookignore if it exists
        let ignore_path = sync_root.join(".lockbookignore");
        if ignore_path.exists() {
            builder.add(&ignore_path);
        }

        let matcher = builder.build().unwrap_or_else(|_| {
            // Fallback: just built-in defaults
            let mut b = GitignoreBuilder::new(sync_root);
            for pattern in BUILTIN_DEFAULTS {
                b.add_line(None, pattern).ok();
            }
            b.build().unwrap()
        });

        Self { matcher }
    }

    /// Check if a path should be ignored. `is_dir` indicates whether the path is a directory.
    pub fn is_ignored(&self, path: &Path, is_dir: bool) -> bool {
        self.matcher
            .matched_path_or_any_parents(path, is_dir)
            .is_ignore()
    }

    /// Generate the default .lockbookignore file at the sync root (first run only).
    pub fn generate_default_file(sync_root: &Path) -> std::io::Result<()> {
        let ignore_path = sync_root.join(".lockbookignore");
        if !ignore_path.exists() {
            fs::write(&ignore_path, DEFAULT_FILE_CONTENTS)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_defaults_work() {
        let dir = tempfile::tempdir().unwrap();
        let rules = IgnoreRules::load(dir.path());

        assert!(rules.is_ignored(&dir.path().join(".git"), true));
        assert!(rules.is_ignored(&dir.path().join("node_modules"), true));
        assert!(rules.is_ignored(&dir.path().join("target"), true));
        assert!(rules.is_ignored(&dir.path().join("__pycache__"), true));
        assert!(rules.is_ignored(&dir.path().join(".DS_Store"), false));
        assert!(rules.is_ignored(&dir.path().join("foo.sqlite"), false));
        assert!(rules.is_ignored(&dir.path().join("foo.sqlite-wal"), false));

        assert!(!rules.is_ignored(&dir.path().join("src"), true));
        assert!(!rules.is_ignored(&dir.path().join("main.rs"), false));
    }

    #[test]
    fn custom_ignore_file() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".lockbookignore"), "*.log\nbuild/\n").unwrap();

        let rules = IgnoreRules::load(dir.path());
        assert!(rules.is_ignored(&dir.path().join("app.log"), false));
        assert!(rules.is_ignored(&dir.path().join("build"), true));
        // Built-in defaults still apply
        assert!(rules.is_ignored(&dir.path().join(".git"), true));
    }

    #[test]
    fn generate_default_file_creates_once() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".lockbookignore");

        assert!(!path.exists());
        IgnoreRules::generate_default_file(dir.path()).unwrap();
        assert!(path.exists());

        let contents = fs::read_to_string(&path).unwrap();
        assert!(contents.contains(".git/"));

        // Second call doesn't overwrite
        fs::write(&path, "custom").unwrap();
        IgnoreRules::generate_default_file(dir.path()).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "custom");
    }
}
