name: lockbook-desktop
base: core18
version: '0.2.24'
summary: The desktop version of Lockbook
description: |
  The best place to store and share thoughts.
grade: devel
confinement: devmode

apps:
  lockbook-desktop:
    extensions: [gnome-3-28]
    command: usr/bin/lockbook

parts:
  lockbook-desktop:
    plugin: rust
    source: ../../../../clients/linux/
