version: '3'

services:
  indexdb:
    image: postgres:12.3
    container_name: indexdb-server-$HASH
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  config_indexdb:
    image: postgres:12.3
    container_name: config_indexdb-server-$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - indexdb
    volumes:
      - $PWD/index_db:/index_db
    entrypoint: >
      /bin/sh -c '\
        while ! pg_isready -h $$INDEX_DB_HOST -p $$INDEX_DB_PORT -U $$INDEX_DB_USER; do echo "Waiting for Postgres to start..." && sleep 0.2; done; \
        psql -wq -h $$INDEX_DB_HOST -p $$INDEX_DB_PORT -U $$INDEX_DB_USER --db $$INDEX_DB_DB -f /index_db/create_db.sql && \
        tail -f /dev/null
      '

  server_tests:
    image: lockbook_server_tests:$HASH
    container_name: lockbook_server_tests-server-$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - indexdb
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        RUST_LOG=lockbook_server=debug cargo test \
      '
