FROM rust
# Use https://rust-lang.github.io/rustup-components-history/ to select one with cargo and rustfmt
RUN rustup toolchain install stable
RUN rustup component add rustfmt --toolchain stable
RUN rustup component add clippy --toolchain stable
WORKDIR integration_tests

# Test depends on core via a relative import
COPY core ../core

# Required to get cargo to get and compile deps but not our source
# https://blog.mgattozzi.dev/caching-rust-docker-builds/
COPY containers/dummy.rs src/lib.rs
COPY integration_tests/Cargo.toml .
COPY integration_tests/Cargo.lock .
RUN cargo build

# Build our source
COPY integration_tests .
# Cargo thinks this file hasn't changed on the filesystem
RUN touch src/lib.rs
RUN cargo build --tests
