FROM core-build AS kotlin-interface-tests
ENV ANDROID_HOME /opt/android-sdk-linux
RUN apt update && apt install -y build-essential openjdk-8-jdk wget curl unzip

# Install android things
RUN wget -q https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip -O android-ndk-r21c-linux-x86_64.zip
RUN unzip -q android-ndk-r21c-linux-x86_64.zip
ENV ANDROID_NDK_HOME=/android-ndk-r21c
RUN cd /opt \
    && wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip \
    && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
RUN yes | sdkmanager --licenses

WORKDIR ..

# Copy android in
COPY clients/android clients/android
WORKDIR clients/android

ENV API_URL=http://lockbook_server:8000

# Move binaries for tests
RUN mkdir -p core/src/main/jniLibs/desktop
RUN mv ../../core/target/release/$(libName) core/src/main/jniLibs/desktop/$(libName)

# Build android
RUN ./gradlew assemble
