FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV ANDROID_HOME /opt/android-sdk-linux
RUN apt update && apt install -y build-essential openjdk-8-jdk wget curl unzip

# Install rust things
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install android things
RUN wget -q https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip -O android-ndk-r21c-linux-x86_64.zip
RUN unzip -q android-ndk-r21c-linux-x86_64.zip
ENV ANDROID_NDK_HOME=/android-ndk-r21c

RUN cd /opt \
    && wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip \
    && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}

ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
RUN yes | sdkmanager --licenses

# Copy android and core in
COPY clients/android clients/android
COPY core core

# Build Core
WORKDIR core
ENV API_URL=unused
RUN cargo build && mv target/release/liblockbook_core.so ../clients/android/core/src/main/jniLibs/

# Build android
WORKDIR ../clients/android
RUN ./gradlew assemble
