version: '3'

services:

  lockbook_server:
    image: server:$HASH
    env_file:
      - ../containers/test.env
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        export STRIPE_SIGNING_SECRET=$$(/usr/bin/stripe listen --api-key $$STRIPE_SECRET --print-secret) && \
        (nohup /usr/bin/stripe listen --api-key $$STRIPE_SECRET --events invoice.payment_failed --events invoice.paid --forward-to $$API_URL/stripe-webhooks &) && \
        RUST_LOG=lockbook_server=debug ./target/release/lockbook-server \
      '

  core_server_tests:
    container_name: core_server_tests-integration-$HASH
    image: core_server_tests:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        LOCKBOOK_DEBUG=1 cargo test --release --no-fail-fast --all -- --nocapture \
      '

  # This is a place you can run tests and modify the db at the same time (server/tests), but there are no longer any
  # such tests so for now this is not used.
  server_tests:
    container_name: server_tests-client-$HASH
    image: server_tests:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        RUST_LOG=lockbook_server=debug cargo test --release \
      '

  swift_interface_tests:
    container_name: swift_interface_tests-swift-$HASH
    image: swift_interface_tests:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        swift test
      '

  csharp_interface_tests:
    container_name: csharp_interface_tests-csharp-$HASH
    image: csharp_interface_tests:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        dotnet test
      '

  kotlin_interface_tests:
    container_name: kotlin_interface_tests-kotlin-$HASH
    image: kotlin_interface_tests:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        gradle testDebugUnitTest \
      '

  performance_bench:
    image: performance:$HASH
    env_file:
      - ../containers/test.env
    depends_on:
      - lockbook_server
    entrypoint: >
      /bin/sh -c '\
        sleep 5 && \
        LOCKBOOK_DEBUG=1 cargo bench -- --profile-time 5 && \
        pprof --svg $$(find . -type f -executable -name "performator-*") simple-create_write_read.profile > simple-create_write_read.svg \
      '