ARG HASH

FROM core:$HASH as core-build

FROM ubuntu:20.04 AS kotlin-interface-tests

ENV ANDROID_HOME /opt/android-sdk-linux
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y build-essential openjdk-8-jdk wget curl unzip

# Install android things
RUN cd /opt \
    && wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip \
    && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
RUN yes | sdkmanager --licenses

# Copy android in
COPY clients/android /clients/android
ENV API_URL=http://lockbook_server:8000

# Move binaries for tests
RUN mkdir -p /clients/android/core/src/main/jniLibs/desktop
WORKDIR /clients/android
COPY --from=core-build /core/target/release/liblockbook_core.so /clients/android/core/src/main/jniLibs/desktop/liblockbook_core.so

# Build android
RUN ./gradlew assemble
