ARG HASH
FROM ubuntu:20.04 AS csharp-interface-tests
ENV DEBIAN_FRONTEND=noninteractive

# Install essentials
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y wget
RUN apt-get install -y curl

# Install dotnet
RUN apt-get install -y gpg
RUN wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
RUN wget https://packages.microsoft.com/config/debian/10/prod.list
RUN mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
RUN chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
RUN chown root:root /etc/apt/sources.list.d/microsoft-prod.list
RUN apt-get update
RUN apt-get install -y apt-transport-https
RUN apt-get update
RUN apt-get install -y dotnet-sdk-3.1

# Copy code
COPY clients/windows clients/windows
RUN mkdir -p clients/windows/core/
COPY --from=core:${HASH} core/target/release/liblockbook_core.so  clients/windows/core

# Build tests
ENV API_URL=http://lockbook_server:8000
WORKDIR clients/windows/test 
RUN dotnet build
