[build.env]
passthrough = [
	"MAX_AUTH_DELAY",
	"INDEX_DB_CONFIG_USER",
	"INDEX_DB_CONFIG_PASS",
	"INDEX_DB_CONFIG_HOST",
	"INDEX_DB_CONFIG_PORT",
	"INDEX_DB_CONFIG_DB",
	"INDEX_DB_CONFIG_CERT",
	"FILES_DB_CONFIG_BUCKET",
	"FILES_DB_CONFIG_REGION",
	"FILES_DB_CONFIG_ACCESS_KEY",
	"FILES_DB_CONFIG_SECRET_KEY",
]
