languageCode = "en-us"
title = "Lockbook"
theme = "hallo"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Lockbook"


[params]

    [[params.links]]
        icon = "apple"
        title = "App Store"
        url = "mailto:mail@example.org"

    [[params.links]]
       	iconset = "fas"
        icon = "terminal"
        title = "Terminal"
        url = "https://github.com/lockbook/lockbook/blob/master/docs/installing-cli.md"

    [[params.links]]
        icon = "android"
        title = "Android"
        url = "https://github.com/lockbook/lockbook/blob/master/docs/installing-android.md"
	
	[[params.links]]
        icon = "windows"
        title = "Windows"
        url = "https://github.com/lockbook/lockbook/blob/master/docs/installing-windows.md"


    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/lockbook/lockbook"

      
     [params.colors]
        background = "#1F2020"
        foreground = "#edf7ff"
        hover = "#ffba82"
