global:
  scrape_interval: 1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'localhost:9093' ]

scrape_configs:
  - job_name: 'metrics'
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'localhost:9100'
  - job_name: 'production'
    static_configs:
      - targets: ['172.31.89.187:9100']
      - labels:
          instance: 'production'
  - job_name: 'github'
    static_configs:
      - targets: ['172.31.27.221:8001']
  - job_name: 'lockbook-server'
    scheme: https
    static_configs:
            - targets: ['api.prod.lockbook.net']
