global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'localhost:9093' ]

scrape_configs:
  - job_name: 'metrics'
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'localhost:9100'
  - job_name: 'load-balancer'
    static_configs:
      - targets:
          - '172.31.43.245:9100'
  - job_name: 'api'
    static_configs:
      - targets: ['172.31.41.113:9100']
      - labels:
          instance: 'api-001'