[package]
name = "drive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
nfsserve = "0.10.1"
tokio = "1.35.1"
cli-rs = "0.1.12"
lb-rs = { path = "../../libs/lb/lb-rs" }
