[package]
name = "lb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lockbook-core = { path = "../../../core" }
lockbook-models = { path = "../../../core/libs/models" }
fuzzy-matcher = "0.3.7"
