/*
 * This source file was generated by the Gradle 'init' task
 */
package net.lockbook;

import org.junit.Test;

public class LBTest {
    @Test public void someLibraryMethodReturnsTrue() {
        System.err.println(Lb.init(""));
    }
}
