use egui::Key;
use windows::Win32::{Foundation::*, UI::Input::KeyboardAndMouse as Win32Key};

pub fn egui_key(wparam: WPARAM) -> Option<Key> {
    Some(match Win32Key::VIRTUAL_KEY(wparam.0 as u16) {
        Win32Key::VK_A => Key::A,
        Win32Key::VK_B => Key::B,
        Win32Key::VK_C => Key::C,
        Win32Key::VK_D => Key::D,
        Win32Key::VK_E => Key::E,
        Win32Key::VK_F => Key::F,
        Win32Key::VK_G => Key::G,
        Win32Key::VK_H => Key::H,
        Win32Key::VK_I => Key::I,
        Win32Key::VK_J => Key::J,
        Win32Key::VK_K => Key::K,
        Win32Key::VK_L => Key::L,
        Win32Key::VK_M => Key::M,
        Win32Key::VK_N => Key::N,
        Win32Key::VK_O => Key::O,
        Win32Key::VK_P => Key::P,
        Win32Key::VK_Q => Key::Q,
        Win32Key::VK_R => Key::R,
        Win32Key::VK_S => Key::S,
        Win32Key::VK_T => Key::T,
        Win32Key::VK_U => Key::U,
        Win32Key::VK_V => Key::V,
        Win32Key::VK_W => Key::W,
        Win32Key::VK_X => Key::X,
        Win32Key::VK_Y => Key::Y,
        Win32Key::VK_Z => Key::Z,
        Win32Key::VK_0 => Key::Num0,
        Win32Key::VK_1 => Key::Num1,
        Win32Key::VK_2 => Key::Num2,
        Win32Key::VK_3 => Key::Num3,
        Win32Key::VK_4 => Key::Num4,
        Win32Key::VK_5 => Key::Num5,
        Win32Key::VK_6 => Key::Num6,
        Win32Key::VK_7 => Key::Num7,
        Win32Key::VK_8 => Key::Num8,
        Win32Key::VK_9 => Key::Num9,
        Win32Key::VK_ESCAPE => Key::Escape,
        Win32Key::VK_RETURN => Key::Enter,
        Win32Key::VK_TAB => Key::Tab,
        Win32Key::VK_LEFT => Key::ArrowLeft,
        Win32Key::VK_RIGHT => Key::ArrowRight,
        Win32Key::VK_UP => Key::ArrowUp,
        Win32Key::VK_DOWN => Key::ArrowDown,
        Win32Key::VK_SPACE => Key::Space,
        Win32Key::VK_DELETE => Key::Backspace,
        Win32Key::VK_F1 => Key::F1,
        Win32Key::VK_F2 => Key::F2,
        Win32Key::VK_F3 => Key::F3,
        Win32Key::VK_F4 => Key::F4,
        Win32Key::VK_F5 => Key::F5,
        Win32Key::VK_F6 => Key::F6,
        Win32Key::VK_F7 => Key::F7,
        Win32Key::VK_F8 => Key::F8,
        Win32Key::VK_F9 => Key::F9,
        Win32Key::VK_F10 => Key::F10,
        Win32Key::VK_F11 => Key::F11,
        Win32Key::VK_F12 => Key::F12,
        Win32Key::VK_HOME => Key::Home,
        Win32Key::VK_PRIOR => Key::PageUp,
        Win32Key::VK_NEXT => Key::PageDown,
        Win32Key::VK_INSERT => Key::Insert,

        _ => return None,
    })
}
