/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Library {
    private static native String hello();

    static {
        System.load("/Users/parth/Documents/lockbook/lockbook/target/debug/liblb_java.dylib");
    }

    public static String helloTest() {
        return Library.hello();
    }
}
