[package]
name = "releaser"
version = "0.7.3"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
gh_release = "0.1.1"
toml = "0.7.0"
toml_edit = "0.19.0"
sha2 = "0.10.2"
hex = "0.4.3"
zip = "0.6.4"
google-androidpublisher3 = "5.0.2"
tokio = "1.20.1"
tempfile = { version = "3.1.0" }
fs_extra = "1.2.0"
regex = "1.7.1"
time = "0.3.20"
