name: lockbook
base: core18
version: '0.2.24'
summary: The CLI version of Lockbook
description: |
  The best place to store and share thoughts.
grade: devel
confinement: devmode

apps:
  lockbook:
    command: usr/bin/lockbook

parts:
  lockbook:
    plugin: rust
    source: ../../../../clients/cli/
