env:
  - HUGO_VERSION="0.50"
  - HUGO_VERSION="0.51"
  - HUGO_VERSION="0.52"
  - HUGO_VERSION="0.53"
  - HUGO_VERSION="0.54.0"
  - HUGO_VERSION="0.55.6"
  - HUGO_VERSION="0.56.3"
  - HUGO_VERSION="0.57.2"
  - HUGO_VERSION="0.58.3"
  - HUGO_VERSION="0.59.1"
  - HUGO_VERSION="0.60.1"
  - HUGO_VERSION="0.61.0"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - hugo version
  - gem install html-proofer

script:
  - cd exampleSite
  - hugo -t hallo-hugo --themesDir ../..
  - htmlproofer public --check-html --disable-external
