name: lockbook
base: core20
version: '0.5.9'
summary: The CLI version of Lockbook
description: |
  The private, polished note-taking platform.
grade: stable
confinement: strict

parts:
  lockbook:
    plugin: rust
    source: https://github.com/lockbook/lockbook.git
    source-tag: 0.4.3
    build-packages:
      - git
    rust-path: ["clients/cli"]

apps:
  lockbook:
    command: bin/lockbook
    plugs:
      - network
      - home
