name: lockbook
base: core20
version: '0.4.2'
summary: The CLI version of Lockbook
description: |
  The best place to store and share thoughts.
grade: stable
confinement: strict

apps:
  lockbook:
    command: bin/lockbook
    plugs:
      - network
      - home

parts:
  lockbook:
    plugin: rust
    source: https://github.com/lockbook/lockbook.git
    build-packages:
      - git
    rust-path: ["clients/cli"]
