name: lockbook-desktop
base: core22
version: '0.5.10'
summary: The linux gui version of Lockbook
description: |
  The private, polished note-taking platform.
grade: stable
confinement: strict

parts:
  lockbook-desktop:
    plugin: rust
    source: https://github.com/lockbook/lockbook.git
    source-tag: 0.4.3
    build-packages:
      - cargo
      - git
      - libgtksourceview-5-dev
      - libgspell-1-dev
    rust-path: ["clients/linux"]

apps:
  lockbook-desktop:
    command: bin/lockbook-desktop
    extensions: [gnome]
    plugs:
      - network
      - home
