/*
 * This source file was generated by the Gradle 'init' task
 */
package net.lockbook;

public class Lb {
    public static native InitRes init(String path);

    static {
        System.load("/Users/parth/Documents/lockbook/lockbook/target/debug/liblb_java.dylib");
    }
}
