package net.lockbook;

public class LbError extends Exception {
    public LbEC kind;
    public String msg;
    public String trace;

    public enum LbEC {
        AccountExists,
        AccountNonexistent,
        AccountStringCorrupted,
        AlreadyCanceled,
        AlreadyPremium,
        AppStoreAccountAlreadyLinked,
        AlreadySyncing,
        CannotCancelSubscriptionForAppStore,
        CardDecline,
        CardExpired,
        CardInsufficientFunds,
        CardInvalidCvc,
        CardInvalidExpMonth,
        CardInvalidExpYear,
        CardInvalidNumber,
        CardNotSupported,
        ClientUpdateRequired,
        CurrentUsageIsMoreThanNewTier,
        DiskPathInvalid,
        DiskPathTaken,
        DrawingInvalid,
        ExistingRequestPending,
        FileNameContainsSlash,
        FileNameTooLong,
        FileNameEmpty,
        FileNonexistent,
        FileNotDocument,
        FileNotFolder,
        FileParentNonexistent,
        FolderMovedIntoSelf,
        InsufficientPermission,
        InvalidPurchaseToken,
        InvalidAuthDetails,
        KeyPhraseInvalid,
        LinkInSharedFolder,
        LinkTargetIsOwned,
        LinkTargetNonexistent,
        MultipleLinksToSameFile,
        NotPremium,
        UsageIsOverDataCap,
        UsageIsOverFreeTierDataCap,
        OldCardDoesNotExist,
        PathContainsEmptyFileName,
        PathTaken,
        RootModificationInvalid,
        RootNonexistent,
        ServerDisabled,
        ServerUnreachable,
        ShareAlreadyExists,
        ShareNonexistent,
        TryAgain,
        UsernameInvalid,
        UsernameNotFound,
        UsernamePublicKeyMismatch,
        UsernameTaken,
        ReReadRequired,
        Unexpected,
    }

}
