name: Android Internal Deployment
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:
jobs:
  DeployAndroid:
    if: github.repository == 'lockbook/lockbook'
    runs-on: [self-hosted, ci]
    env:
      ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}
      ANDROID_RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
      ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
      GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
      ANDROID_RELEASE_STORE_BASE64: ${{ secrets.ANDROID_RELEASE_STORE_BASE64 }}
      NIXPKGS_ALLOW_UNFREE: 1
      NIXPKGS_ACCEPT_ANDROID_SDK_LICENSE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Configure PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Setup Machine
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
          cargo install cargo-ndk
      - name: Decode Keystore
        run: |
          echo $ANDROID_RELEASE_STORE_BASE64 | base64 --decode > $HOME/lockbook-android-upload.keystore
          echo "ANDROID_RELEASE_STORE_FILE=$HOME/lockbook-android-upload.keystore" >> $GITHUB_ENV
      - name: deploy android
        run: nix-shell clients/android --command "cargo r -p lbdev releaser android internal-play-store"
