name: Apple Deployment

on:
  push:
    branches: [ master ]

jobs:
  DeployApple:
    if: github.repository == 'lockbook/lockbook'
    runs-on: [self-hosted, macOS]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4 
    - name: Build WS
      run: |
        cargo r -p lbdev apple ws all
