name: Deploy Flatpak

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-flatpak:
    if: github.repository == 'lockbook/lockbook'
    runs-on: [self-hosted, ci]
    steps:
    - uses: actions/checkout@v4 
    - name: Deploy public site
    - run: nix-shell -p python3 python313Packages.aiohttp python313Packages.tomlkit --command "cargo run -p lbdev -- releaser desktop flatpak"

