name: Github Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run release script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo run -p lbdev -- releaser github-release
  
  call_publish:
    needs: release
    uses: ./.github/workflows/publish-crate.yml
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  call_publish_flatpak:
    needs: release
    uses: ./.github/workflows/flatpak.yml
    secrets: inherit

  deploy_android:
    needs: release
    uses: ./.github/workflows/android.yml
    with:
      environment: prod-play-store
    secrets: inherit

  deploy_windows:
    needs: release
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  deploy_windows_arm:
    needs: release
    uses: ./.github/workflows/windows-arm.yml
    secrets: inherit

  deploy_apple:
    needs: release
    uses: ./.github/workflows/apple.yml
    with:
      release: true
    secrets: inherit

  deploy_aur:
    needs: release
    uses: ./.github/workflows/aur.yml
    secrets: inherit

  deploy_linux:
    needs: release
    uses: ./.github/workflows/linux-release.yml
    secrets: inherit

  deploy_snap:
    needs: release
    uses: ./.github/workflows/snap.yml
    secrets: inherit