name: Master

on:
  push:
    branches: [ master ]

jobs:
  deploy-site:
    uses: ./.github/workflows/public-site.yml
    secrets: inherit

  deploy-android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  deploy-apple:
    uses: ./.github/workflows/apple.yml
    secrets: inherit

  build-linux-server:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-server
      artifact-name: lockbook-server

  build-linux-cli:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook
      artifact-name: lockbook-cli-linux

  build-linux-egui:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-egui
      artifact-name: lockbook-egui-linux

  build-linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-linux
      artifact-name: lockbook-linux

  build-windows-cli:
    uses: ./.github/workflows/windows-build.yml
    with:
      package: lockbook
      artifact-name: lockbook-cli-windows

  build-windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      package: lockbook-windows
      artifact-name: lockbook-windows

  build-windows-egui:
    uses: ./.github/workflows/windows-build.yml
    with:
      package: lockbook-egui
      artifact-name: lockbook-egui-windows

  build-windows-installer:
    uses: ./.github/workflows/windows-build.yml
    with:
      package: winstaller
      artifact-name: winstaller
