name: Master

on:
  push:
    branches: [ master ]

jobs:
  deploy-site:
    uses: ./.github/workflows/public-site.yml
    secrets: inherit

  deploy-android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  deploy-apple:
    uses: ./.github/workflows/apple.yml
    secrets: inherit
