name: Master

on:
  push:
    branches: [ master ]

jobs:
  deploy-site:
    uses: ./.github/workflows/public-site.yml
    secrets: inherit

  deploy-android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  deploy-apple:
    uses: ./.github/workflows/apple.yml
    secrets: inherit

  build-linux-server:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-server
      artifact-name: lockbook-server
      binary-name: lockbook-server

  build-linux-cli:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook
      artifact-name: lockbook-cli-linux
      binary-name: lockbook

  build-linux-egui:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-egui
      artifact-name: lockbook-egui-linux
      binary-name: lockbook-egui

  build-linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      package: lockbook-linux
      artifact-name: lockbook-linux
      binary-name: lockbook-linux
