name: Publish Crate

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
    secrets:
      CRATES_IO_API_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish lb-rs
        run: |
          cargo run -p lbdev -- releaser publish-crate lb-rs
      - name: Publish lb-fs
        run: |
          cargo run -p lbdev -- releaser publish-crate lb-fs
      - name: Publish cli
        run: |
          cargo run -p lbdev -- releaser publish-crate lockbook
      
