name: Release
on:
  workflow_dispatch:
    inputs:
      release_option:
        description: 'Release option'
        required: true
        default: 'github-release'
        type: choice
        options:
          - github-release
          - all
      platform:
        description: 'Platform to run the workflow on'
        required: true
        default: 'macos'
        type: choice
        options:
          - macos
          - linux
          - windows
jobs:
  release:
    runs-on: ${{ github.event.inputs.platform }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run release script
        run: |
          cargo run -p releaser -- ${{ github.event.inputs.release_option }}
